{
 "title": "h2olock",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "energy_production", "label": "energy_production", "query": "energy_production" },
   { "name": "humidity", "label": "humidity", "query": "humidity" },
   { "name": "line_loads", "label": "line_loads", "query": "line_loads" },
   { "name": "solar_radiation", "label": "solar_radiation", "query": "solar_radiation" },
   { "name": "temperature", "query": "temperature" },
   { "name": "wind_speed", "label": "wind_speed", "query": "wind_speed" },
   { "name": "Temp_in", "label": "Temp_in", "query": "Temp_in" },
   { "name": "Temp_out", "label": "Temp_out", "query": "Temp_out" },
   { "name": "hum_out", "label": "hum_out", "query": "hum_out" },
   { "name": "hum_in", "label": "hum_in", "query": "hum_in" },
   { "name": "solar_rad", "label": "solar_rad", "query": "solar_rad" },
   { "name": "rain", "label": "rain", "query": "rain" },
   { "name": "wind_dir", "label": "wind_dir", "query": "wind_dir" },
   { "name": "variable", "query": "show tables;" },
   { "name": "presion", "label": "presion", "query": "presion" }
  ]
 },
 "panels": [
  {
   "title": "Sensors data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "select valores as temperature,$__time(date) from tempout  where  $Temp_out = 'Temp_out' and $__timeFilter(date)\r\n\r\n\r\n\r\n"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select valores as windSpeed,$__time(date) from windspeed  where $wind_speed = 'Wind_Speed' AND $__timeFilter(date)\r\n#select Wind, date as time from datos where $wind_speed = 'Wind_Speed' AND $__timeFilter(date)"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select valores as solarRad,$__time(date) from solarrad where $solar_rad = 'solar_rad' and $__timeFilter(date);\r\n#select Solar_Rad,date as time from datos where $solar_rad = 'solar_rad'  and $__timeFilter(date)"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select valores as humedad,$__time(date) from humout  where $hum_out = 'hum_out' AND $__timeFilter(date) ;\r\n#select Hum_Out,date as time from datos where $hum_out = 'hum_out' AND $__timeFilter(date)"
    },
    {
     "rawSql": "select valores as rain,$__time(date) from Rain where $rain = 'rain' AND $__timeFilter(date)\r\n#select Rain,date as time from datos where $rain = 'rain' AND $__timeFilter(date)"
    },
    {
     "rawSql": "#select valores as winDir, $__time(date) from winddir   where $wind_dir = 'wind_dir' AND $__timeFilter(date)\r\n"
    },
    {
     "rawSql": "select valores as presion,$__time(date) from presion  where  $presion = 'presion' and $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT valores as temperatura, $__time(date) FROM tempout WHERE $__timeFilter(date) \r\n#select TempOut, date as time from data "
    }
   ]
  },
  { "title": "video_streaming", "type": "innius-video-panel", "gridPos": { "h": 10, "w": 5, "x": 12, "y": 6 } },
  {
   "title": "Historic Percentage covered",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "#SELECT date, value FROM h2olock.solar_radiation\r\nselect valores, $__time(date) from tempout where $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "#SELECT date as time, value FROM h2olock.line_loads\r\nselect valores as rain, $__time(date) from rain where $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "presion",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT valores, $__time(date) from presion where $__timeFilter(date) "
    }
   ]
  },
  { "title": "Percentage covered", "gridPos": { "h": 5, "w": 2, "x": 17, "y": 10 } },
  {
   "title": "Load Cell",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select cell_1,cell_2,cell_3,cell_4,cell_5, $__time(date) from cells where $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "#SELECT date as time, value FROM h2olock.humidity\r\nselect valores, $__time(date) from humout where $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Solar radiation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "#SELECT date, value FROM h2olock.solar_radiation\r\nselect valores, $__time(date) from solarrad where $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "wind speed & direction",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select s.valores as direccion, $__time(s.date), v.valores as speed \r\nfrom winddir s \r\ninner join windspeed v \r\non s.date = v.date \r\nwhere $__timeFilter(v.date) "
    }
   ]
  },
  {
   "title": "Evaporation and water quality",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "#SELECT value as temperature, date FROM h2olock.temperature\r\nSELECT TempOut ,TempIn, date as time from datos"
    },
    {
     "dataset": "h2olock",
     "rawSql": "#SELECT value as solar_radiation, date FROM h2olock.solar_radiation\r\n#SELECT `temp_in`, date as time from data "
    }
   ]
  },
  { "title": "Percentage of water", "gridPos": { "h": 7, "w": 3, "x": 18, "y": 22 } }
 ]
}