{
 "title": "humedad/temp",
 "time": { "from": "2023-05-10T00:00:00.000Z", "to": "2023-05-10T16:30:00.000Z" },
 "templating": {
  "list": [
   { "name": "energy_production", "label": "energy_production", "query": "energy_production" },
   { "name": "humidity", "label": "humidity", "query": "humidity" },
   { "name": "line_loads", "label": "line_loads", "query": "line_loads" },
   { "name": "solar_radiation", "label": "solar_radiation", "query": "solar_radiation" },
   { "name": "temperature", "query": "temperature" },
   { "name": "wind_speed", "label": "wind_speed", "query": "wind_speed" }
  ]
 },
 "panels": [
  {
   "title": "H2OLOCK",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "select value,date as time from energy_production where $energy_production = 'energy_production'"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select value,date as time from humidity where $humidity = 'humidity';"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select value,date as time from line_loads where $line_loads = 'line_loads';"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select value,date as time from solar_radiation where $solar_radiation = 'solar_radiation';"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select value,date as time from temperature where $temperature = 'temperature';"
    },
    {
     "dataset": "h2olock",
     "rawSql": "select value,date as time from wind_speed where $wind_speed = 'wind_speed';"
    }
   ]
  },
  {
   "title": "energy_production",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT value, date as time FROM h2olock.energy_production "
    }
   ]
  },
  {
   "title": "line_loads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT date as time, value FROM h2olock.line_loads"
    }
   ]
  },
  {
   "title": "Percentage of water",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT value FROM h2olock.temperature"
    }
   ]
  },
  { "title": "video_streaming", "type": "innius-video-panel", "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 } },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT date as time, value FROM h2olock.humidity"
    }
   ]
  },
  {
   "title": "solar_radiation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT date, value FROM h2olock.solar_radiation"
    }
   ]
  },
  {
   "title": "Evaporation and water quality",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT value as temperature, date FROM h2olock.temperature"
    },
    {
     "dataset": "h2olock",
     "rawSql": "SELECT value as solar_radiation, date FROM h2olock.solar_radiation"
    }
   ]
  },
  {
   "title": "wind_speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT date as time, value FROM h2olock.wind_speed "
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "h2olock",
     "rawSql": "SELECT value, date as time FROM h2olock.temperature"
    }
   ]
  }
 ]
}