version: '2'

services:

mysql:
  image : mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ~/db/mysql:/var/lib/mysql
    - ./init-dump:/docker-entrypoint-initdb.d
  environment:
    TERM: xterm
    APP_ENV: dev
    MYSQL_USER: user
    MYSQL_PASSWORD: usuario123
    MYSQL_DATABASE: proyecto
    MYSQL_ROOT_PASSWORD: root
  container_name: mysql

  grafana:
    image: grafana/grafana:7.3.7     
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - mysql:5.7
    volumes:
      - ./data_grafana:/var/lib/grafana

volumes:
  data_grafana:

  