version: '3.7'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    links:
      - mysql
    volumes:
      - data_grafana:/var/lib/grafana
    ports:
      - 3000:3000

  mysql:
    image: mysql:8
    container_name: mysql_grafana
    command: --init-file /data/application/proyecto.sql
    volumes:
      - ./proyecto.sql:/data/application/proyecto.sql
      - mysql_grafana:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=prueba
    ports:
      - 3306:3306

volumes:
  mysql_grafana:
  data_grafana:
